### ISSUE TITLE
plugin completly broken

### ISSUE THREAD

**Issue by LU15W1R7H** [levnikmyskin/hyprland-virtual-desktops#44]
I don't know what I'm doing wrong, but for me this, plugin is completly broken!
It's hard for me to even describe what's going on...

First of all, the desks cannot be switched as I would have expected it. The windows I have open on my two monitors, don't live on the same desk...

I tried to do a `hyprtl dispatch vdeskreset`, but then everything goes haywire. Just moving the mouse from one monitor to the other makes the windows on the two monitors switch and I get some empty gap (wihtout windows) in the middle of one of the monitors. It's extremly weird.

I'm on NixOS running Hyprland v40.

**Comment by levnikmyskin** [comment]
Hi, sometimes this also happens to me, and it's most likely due to monitors layout changing (in your case, internal monitor going off). 
I think this happens because the plugin by default tries to remember layouts and workspaces, but it's not easy to track when the workspace change is triggered by the user or by hyprland.

I'll take a look into this. In the meantime, if vdeskreset doesn't work, you could try specify `rememberlayout = none` in the [configuration options](https://github.com/levnikmyskin/hyprland-virtual-desktops?tab=readme-ov-file#configuration-values)

**Comment by LU15W1R7H** [comment]
Yes I agree, changing layouts does seem to cause this. Also when first having no monitor connected and my internal monitor turned on and then just connecting a 2nd monitor causes a bug, where there is a weird workspace setup.

Setting `rememberlayout = none` still makes the problem happen. To only apparently sure way to have a working setup, is to start hyprland with all monitors I want plugged in (for now just one addiontal one) and then not messing with the monitor layout.

**Comment by levnikmyskin** [comment]
Can you check if this happens on hyprland 0.39.1 as well?

**Comment by LU15W1R7H** [comment]
I'm having a hard time downgrading on NixOS... Using an old `flake.lock` gives a build error...
I will however try to investigate the error further and provide new information.

**Comment by levnikmyskin** [comment]
I see. I use arch, so unfortunately cannot really help there. Also, you forgot to say which tool you're using to shutdown/ power up the monitors

**Comment by LU15W1R7H** [comment]
Usually I do use kanshi, but unfortunatly it doesn't work for hyprland v40, see hyprwm/Hyprland#5978.
So instead I currently modify my monitor setup manually using `hyprctl keyword monitor ...`

**Comment by levnikmyskin** [comment]
Yeah, this happens every now and then unfortunately. Just yesterday night I opened [this PR](https://github.com/fdev31/wlr-layout-ui/pull/9) on another small tool which is using hyprctl directly.
Until hyprland stabilises, it might be a better solution IMO.

Anyway, please also attach hyprland logs of when this behaviour happens

**Comment by levnikmyskin** [comment]
Hi! The kanshi problem was fixed upstream. Does this happen with kanshi too? If you can reproduce it, could you attach the hyprland log?

**Comment by adam-neeley** [comment]
Maybe it was fixed. I don't think I've ever experienced this issue, except when I first installed the plugin (on NixOS). Either logging out or rebooting solved the issue; I don't recall.

**Comment by levnikmyskin** [comment]
That's good to know! Unfortunately, I think this problem (vdesks going crazy etc) is still present, despite rather unpredictable. One day I'll look into it. Most likely, it will require changes in Hyprland itself to send an event before/after workspaces have been "adjusted", following a monitor connection/disconnection

**Comment by adam-neeley** [comment]
Hmm, come to think of it I generally keep my monitors on at all times. I will test when I have access to them.

It's remarkable that your first plugin is so good considering the complex nature of the situation. I'm repeating myself but virtual desktops kept me on Plasma until now so I'm very grateful for this project.

**Comment by levnikmyskin** [comment]
Thanks for the kind words. And yes, I also just can't work without this metaphor anymore :)

**Comment by levnikmyskin** [comment]
hey, just curious. Is this still happening? I feel like on aquamarine this stuff kind of fixed itsef (?)

**Comment by luiswirth** [comment]
I don't use this plugin anymore, since it wasn't working for me at the time.

**Comment by WhySoBad** [comment]
> hey, just curious. Is this still happening? I feel like on aquamarine this stuff kind of fixed itsef (?)

Hi, I've had this issue for some time now. 

I can't really reproduce it but it happens to me almost every time I want to move a window from say `vdesk 1` to `vdesk 2` after on `vdesk 1` all three monitors were populated with a window. 

On `vdesk 2` the window in some kind of background layer and I can open other windows on top of it. Sometimes new windows created on `vdesk 2` then are buggy and take space but get invisible. 

In most of the cases I'm able to "fix" this issue by going to `vdesk 3` and populating every monitor with a window and then switching back to `vdesk 2`. If this does not work I repeat the same process with `vdesk 4` etc. 

I've suspected hyprland to cause this bug for quite some time now but I'm getting the feeling it's this plugin which causes this behavior. I've not yet had the time to dig through the source to find possible reasons for this behavior but I'll have a look in the next weeks and let you know if I find something

**Comment by levnikmyskin** [comment]
Thank you for the details. For this weird behaviours, I've always suspected the code that handles the monitor connection/disconnection. When this happens, hyprland re-adapts the windows on the workspaces, possibly messing up with the virtual desktop layouts.
I've never found a proper way to deal with this, othert than what I did in the code so far. I think only way would be for hyprland to expose an event for "after" monitor connection/disconnection actions (i.e., after hyprland is done doing its stuff upon monitor connection/disconnection)

**Comment by WhySoBad** [comment]
But when the code which handles the monitor connection/disconnection is the culprit I should not have any issues on my desktop where all monitors are "hardwired" and connected at boot or am I wrong?

**Comment by levnikmyskin** [comment]
mh not really, because the monitor connection event would anyway be sent twice (assuming you have two monitors) by Hyprland

**Comment by WhySoBad** [comment]
Fair enough, I just wondered because on my laptop I've never had any problems. I only use the laptop with it's inbuilt monitor but still have the plugin enabled.

**Comment by boostd** [comment]
still occurring for me on the laptop. closing/opening the lid (turning off/on the internal monitor) messes everything up. i am on the latest hyprland release and latest version of the plugin

anyways thanks for your work on this plugin. it usually works and is usually amazing

**Comment by a-priestley** [comment]
I'm having similar issues. Hopefully I can help by describing what happens on my setup.

I use a laptop, and in my config I have:
```Hypr
# bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, preferred, auto-left, auto"
bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, preferred, 0x0, auto"
# trigger when the switch is turning on
bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
```
So when I close the lid, it disables the built-in monitor.

When I have an external monitor plugged in, vdesks are shifted over to it like you would expect, but when I open the lid back up, everything breaks. In the existing vdesk, there is no longer a workspace for the external monitor, so I cannot focus it or move windows to it.

Interestingly, when I unplug the external monitor with the lid open and then plug it back in, everything works correctly -- workspaces are shifted over to the internal monitor on disconnect, then on reconnect, it is restored (ws 1 on internal, ws 2 on external, etc). I am using `rememberlayout = none` right now, but this seems to happen with any of the three options.

My monitor configuration is very simple:
```Hypr
monitor = eDP-1, preferred, 0x0, auto
monitor = , preferred, auto, auto
```

**Comment by boostd** [comment]
> I'm having similar issues

yep i think we are having the same issue, you just gave it a much better description :D
i have the exact same symptoms down to the dot.

unfortunately i have not discovered a workaround and i'm just dealing with it since the plugin is much too valuable to stop using.
sometimes what helps is moving the windows around/to different desktops & spamming `hyprctl dispatch vdeskreset` but it is nothing consistent.

my monitor settings for reference
```
  hyprland.monitorConfig = [
    ",preferred,auto,1"
    "eDP-1, 1920x1080@60.02000, 0x0, 1"
    "desc:Dell Inc. DELL U2719D 8SP4Y13, 2560x1440@59.95100, 1920x0, 1"
    "desc:Dell Inc. DELL U27198 9RP4Y13, 2560x1440@59.95100, 4480x0, 1"
  ];
```
